services:
  dns-service:
    container_name: dns-service
    build:
      context: ./backend/dns-service
      dockerfile: dns-service.dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/dns_service
      - SECRET_KEY=your_secret_key_here
      - FLASK_ENV=development
      - DEBUG=True
    depends_on:
      - db

  db:
    container_name: dm-db
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dns_service
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:
